<?php

declare(strict_types=1);

namespace App\Product\Infrastructure\Cli;

use App\Product\Application\CreateProduct\CreateProductCommand;
use App\Product\Application\IndexProduct\IndexProductCommand;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Messenger\MessageBusInterface;

#[AsCommand(
    name: 'app:seed:siroko-products',
    description: 'Seeds the database with Siroko cycling products and indexes them in Qdrant',
)]
final class SeedSirokoProductsCommand extends Command
{
    private const array PRODUCTS = [
        ["name" => "SRX Ultra Warm Gray", "semanticDescription" => "SRX Ultra Warm Gray es un Chaleco térmico ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Premier-W Gray", "semanticDescription" => "SRX Premier-W Gray es un Culote largo ciclismo mujer para Mujer. Disponible en Gris. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "SRX Supreme Gray", "semanticDescription" => "SRX Supreme Gray es un Culote largo ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "Horizon Light Green", "semanticDescription" => "Horizon Light Green es un Gorra resistente al agua cicloturismo para unisex. Disponible en Verde. Confeccionado en Poliamida."],
        ["name" => "Globe-trot Indigo", "semanticDescription" => "Globe-trot Indigo es un Gorra resistente al agua cicloturismo para unisex. Disponible en Azul. Confeccionado en Poliamida."],
        ["name" => "Journey Light Green", "semanticDescription" => "Journey Light Green es un Sudadera cicloturismo hombre para Hombre. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "Soulful Sand", "semanticDescription" => "Soulful Sand es un Sudadera cicloturismo mujer para Mujer. Disponible en Beige, Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "Embrace Orange", "semanticDescription" => "Embrace Orange es un Bandana cicloturismo para Mujer. Disponible en Naranja. Confeccionado en Algodón."],
        ["name" => "Shoall Light Green", "semanticDescription" => "Shoall Light Green es un Bandana cicloturismo para Hombre. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Rush Black", "semanticDescription" => "Rush Black es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Negro. Confeccionado en Algodón."],
        ["name" => "Herb Green", "semanticDescription" => "Herb Green es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Exploring Sand", "semanticDescription" => "Exploring Sand es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Algodón."],
        ["name" => "Reef Light Green", "semanticDescription" => "Reef Light Green es un Camiseta holgada manga corta cicloturismo mujer para Mujer. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Feel Sand", "semanticDescription" => "Feel Sand es un Camiseta holgada manga corta cicloturismo mujer para Mujer. Disponible en Beige. Confeccionado en Algodón."],
        ["name" => "Pilgrim Sand", "semanticDescription" => "Pilgrim Sand es un Camiseta técnica manga corta cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Poliéster, Elastano."],
        ["name" => "Pilgrim Orange", "semanticDescription" => "Pilgrim Orange es un Camiseta técnica manga corta cicloturismo hombre para Hombre. Disponible en Naranja. Confeccionado en Poliéster, Elastano."],
        ["name" => "Map Purple", "semanticDescription" => "Map Purple es un Camiseta técnica manga corta cicloturismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "Map Black", "semanticDescription" => "Map Black es un Camiseta técnica manga corta cicloturismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "Daytrip Indigo", "semanticDescription" => "Daytrip Indigo es un Pantalón corto cicloturismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "Daytrip Camel", "semanticDescription" => "Daytrip Camel es un Pantalón corto cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Poliamida, Elastano."],
        ["name" => "Turf Gray Green", "semanticDescription" => "Turf Gray Green es un Pantalón corto cicloturismo mujer para Mujer. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Turf Purple", "semanticDescription" => "Turf Purple es un Pantalón corto cicloturismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "Tour Black", "semanticDescription" => "Tour Black es un Culote corto sin tirantes cicloturismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "Roam Black", "semanticDescription" => "Roam Black es un Culote corto sin tirantes cicloturismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "ST1 Black", "semanticDescription" => "ST1 Black es un Calcetines cicloturismo media caña para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "ST1 Green", "semanticDescription" => "ST1 Green es un Calcetines cicloturismo media caña para unisex. Disponible en Verde. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Emberly Brown", "semanticDescription" => "Emberly Brown es un Sobrecamisa de gravel para verano mujer para Mujer. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "Stoneway Black", "semanticDescription" => "Stoneway Black es un Sobrecamisa de gravel para verano hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Green", "semanticDescription" => "GS2 Green es un Calcetines caña media gravel para unisex. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Black", "semanticDescription" => "GS2 Black es un Calcetines caña media gravel para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Blue", "semanticDescription" => "GS2 Blue es un Calcetines caña media gravel para unisex. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Burgundy", "semanticDescription" => "GS2 Burgundy es un Calcetines caña media gravel para unisex. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "S3 Blue", "semanticDescription" => "S3 Blue es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Azul. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Black", "semanticDescription" => "S3 Black es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Gray", "semanticDescription" => "S3 Gray es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Gris. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Purple", "semanticDescription" => "S3 Purple es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Morado. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "HE Cover Black", "semanticDescription" => "HE Cover Black es un Funda impermeable casco ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster."],
        ["name" => "BX Colombier", "semanticDescription" => "BX Colombier es un Culote corto reciclado ciclismo mujer para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "BX Semnoz", "semanticDescription" => "BX Semnoz es un Culote corto reciclado ciclismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "BX Brocken", "semanticDescription" => "BX Brocken es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "SRX Ultra Warm Gray", "semanticDescription" => "SRX Ultra Warm Gray es un Chaleco térmico ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Premier-W Gray", "semanticDescription" => "SRX Premier-W Gray es un Culote largo ciclismo mujer para Mujer. Disponible en Gris. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "SRX Supreme Gray", "semanticDescription" => "SRX Supreme Gray es un Culote largo ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "Horizon Light Green", "semanticDescription" => "Horizon Light Green es un Gorra resistente al agua cicloturismo para unisex. Disponible en Verde. Confeccionado en Poliamida."],
        ["name" => "Globe-trot Indigo", "semanticDescription" => "Globe-trot Indigo es un Gorra resistente al agua cicloturismo para unisex. Disponible en Azul. Confeccionado en Poliamida."],
        ["name" => "Journey Light Green", "semanticDescription" => "Journey Light Green es un Sudadera cicloturismo hombre para Hombre. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "Soulful Sand", "semanticDescription" => "Soulful Sand es un Sudadera cicloturismo mujer para Mujer. Disponible en Beige, Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "Embrace Orange", "semanticDescription" => "Embrace Orange es un Bandana cicloturismo para Mujer. Disponible en Naranja. Confeccionado en Algodón."],
        ["name" => "Shoall Light Green", "semanticDescription" => "Shoall Light Green es un Bandana cicloturismo para Hombre. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Rush Black", "semanticDescription" => "Rush Black es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Negro. Confeccionado en Algodón."],
        ["name" => "Herb Green", "semanticDescription" => "Herb Green es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Exploring Sand", "semanticDescription" => "Exploring Sand es un Camiseta holgada manga corta cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Algodón."],
        ["name" => "Reef Light Green", "semanticDescription" => "Reef Light Green es un Camiseta holgada manga corta cicloturismo mujer para Mujer. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Feel Sand", "semanticDescription" => "Feel Sand es un Camiseta holgada manga corta cicloturismo mujer para Mujer. Disponible en Beige. Confeccionado en Algodón."],
        ["name" => "Pilgrim Sand", "semanticDescription" => "Pilgrim Sand es un Camiseta técnica manga corta cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Poliéster, Elastano."],
        ["name" => "Pilgrim Orange", "semanticDescription" => "Pilgrim Orange es un Camiseta técnica manga corta cicloturismo hombre para Hombre. Disponible en Naranja. Confeccionado en Poliéster, Elastano."],
        ["name" => "Map Purple", "semanticDescription" => "Map Purple es un Camiseta técnica manga corta cicloturismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "Map Black", "semanticDescription" => "Map Black es un Camiseta técnica manga corta cicloturismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "Daytrip Indigo", "semanticDescription" => "Daytrip Indigo es un Pantalón corto cicloturismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "Daytrip Camel", "semanticDescription" => "Daytrip Camel es un Pantalón corto cicloturismo hombre para Hombre. Disponible en Beige. Confeccionado en Poliamida, Elastano."],
        ["name" => "Turf Gray Green", "semanticDescription" => "Turf Gray Green es un Pantalón corto cicloturismo mujer para Mujer. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Turf Purple", "semanticDescription" => "Turf Purple es un Pantalón corto cicloturismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "Tour Black", "semanticDescription" => "Tour Black es un Culote corto sin tirantes cicloturismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "Roam Black", "semanticDescription" => "Roam Black es un Culote corto sin tirantes cicloturismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "ST1 Black", "semanticDescription" => "ST1 Black es un Calcetines cicloturismo media caña para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "ST1 Green", "semanticDescription" => "ST1 Green es un Calcetines cicloturismo media caña para unisex. Disponible en Verde. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Emberly Brown", "semanticDescription" => "Emberly Brown es un Sobrecamisa de gravel para verano mujer para Mujer. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "Stoneway Black", "semanticDescription" => "Stoneway Black es un Sobrecamisa de gravel para verano hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Green", "semanticDescription" => "GS2 Green es un Calcetines caña media gravel para unisex. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Black", "semanticDescription" => "GS2 Black es un Calcetines caña media gravel para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Blue", "semanticDescription" => "GS2 Blue es un Calcetines caña media gravel para unisex. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "GS2 Burgundy", "semanticDescription" => "GS2 Burgundy es un Calcetines caña media gravel para unisex. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "S3 Blue", "semanticDescription" => "S3 Blue es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Azul. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Black", "semanticDescription" => "S3 Black es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Gray", "semanticDescription" => "S3 Gray es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Gris. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S3 Purple", "semanticDescription" => "S3 Purple es un Calcetines caña alta ciclismo invierno para unisex. Disponible en Morado. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "HE Cover Black", "semanticDescription" => "HE Cover Black es un Funda impermeable casco ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster."],
        ["name" => "BX Colombier", "semanticDescription" => "BX Colombier es un Culote corto reciclado ciclismo mujer para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "BX Semnoz", "semanticDescription" => "BX Semnoz es un Culote corto reciclado ciclismo mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "BX Brocken", "semanticDescription" => "BX Brocken es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "BX Terres", "semanticDescription" => "BX Terres es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Marrón. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "SRX Fusion", "semanticDescription" => "SRX Fusion es un Culote corto biodegradable ciclismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "SRX Blend", "semanticDescription" => "SRX Blend es un Culote corto biodegradable ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "MTB Slack Blue", "semanticDescription" => "MTB Slack Blue es un Sudadera capucha MTB hombre para Hombre. Disponible en Azul. Confeccionado en Algodón, Poliéster, Elastano."],
        ["name" => "MTB Slack Gray", "semanticDescription" => "MTB Slack Gray es un Sudadera capucha MTB hombre para Hombre. Disponible en Gris. Confeccionado en Algodón, Poliéster, Elastano."],
        ["name" => "J2 Nivolet", "semanticDescription" => "J2 Nivolet es un Chaquetas de lluvia ciclismo hombre para Hombre. Disponible en Azul. Confeccionado en Nailon, Poliuretano."],
        ["name" => "J2-W Zarza", "semanticDescription" => "J2-W Zarza es un Chaquetas de lluvia ciclismo mujer para Mujer. Disponible en Azul. Confeccionado en Nailon, Poliuretano."],
        ["name" => "Rutted-W Brown", "semanticDescription" => "Rutted-W Brown es un Camiseta de gravel manga larga algodón mujer para Mujer. Disponible en Marrón. Confeccionado en Algodón."],
        ["name" => "Rutted Green", "semanticDescription" => "Rutted Green es un Camiseta de gravel manga larga algodón hombre para Hombre. Disponible en Verde. Confeccionado en Algodón."],
        ["name" => "Rutted Burgundy", "semanticDescription" => "Rutted Burgundy es un Camiseta de gravel manga larga algodón hombre para Hombre. Disponible en Rojo. Confeccionado en Algodón."],
        ["name" => "SRX Sella", "semanticDescription" => "SRX Sella es un Calcetines de ciclismo con lana merino para unisex. Disponible en Rosa. Confeccionado en Poliamida, Lana Merino, Poliéster, Acrílico, Elastano."],
        ["name" => "GS1 Lilac", "semanticDescription" => "GS1 Lilac es un Calcetines de gravel para unisex. Disponible en Morado. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "GS1 Light Yellow", "semanticDescription" => "GS1 Light Yellow es un Calcetines de gravel para unisex. Disponible en Amarillo. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "GS1 Tile", "semanticDescription" => "GS1 Tile es un Calcetines de gravel para unisex. Disponible en Rojo. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "GS1 Yellow", "semanticDescription" => "GS1 Yellow es un Calcetines de gravel para unisex. Disponible en Amarillo. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Capst Green", "semanticDescription" => "Capst Green es un Gorra de gravel para unisex. Disponible en Verde. Confeccionado en Poliéster."],
        ["name" => "Spugla-W", "semanticDescription" => "Spugla-W es un Camiseta de gravel mujer para unisex. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "HB Thermal Black", "semanticDescription" => "HB Thermal Black es un Cinta orejera ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "HB Thermal Burgundy", "semanticDescription" => "HB Thermal Burgundy es un Cinta orejera ciclismo para unisex. Disponible en Rojo. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J3 Souplesse", "semanticDescription" => "J3 Souplesse es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Aravis", "semanticDescription" => "SRX Aravis es un Calcetines de ciclismo con lana merino para unisex. Disponible en Rojo. Confeccionado en Poliamida, Lana Merino, Poliéster, Acrílico, Elastano."],
        ["name" => "M9-W Scanuppia Brown", "semanticDescription" => "M9-W Scanuppia Brown es un Maillot ciclismo manga larga sin cremallera mujer para Mujer. Disponible en Marrón. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "M9-W Scanuppia Purple", "semanticDescription" => "M9-W Scanuppia Purple es un Maillot ciclismo manga larga sin cremallera mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "NW Shield Black", "semanticDescription" => "NW Shield Black es un Braga cuello ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida."],
        ["name" => "NW Shield Burgundy", "semanticDescription" => "NW Shield Burgundy es un Braga cuello ciclismo para unisex. Disponible en Rojo. Confeccionado en Poliamida."],
        ["name" => "GM6 Rideout Green", "semanticDescription" => "GM6 Rideout Green es un Maillot de gravel manga larga hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM6 Rideout Black", "semanticDescription" => "GM6 Rideout Black es un Maillot de gravel manga larga hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "DW Valdres Black", "semanticDescription" => "DW Valdres Black es un Maillot térmico capucha ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "DW Finestre Black", "semanticDescription" => "DW Finestre Black es un Camiseta interior térmica capucha ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "M9 Scanuppia Black", "semanticDescription" => "M9 Scanuppia Black es un Maillot ciclismo manga larga sin cremallera hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "M9 Scanuppia Beige", "semanticDescription" => "M9 Scanuppia Beige es un Maillot ciclismo manga larga sin cremallera hombre para Hombre. Disponible en Beige. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Apalache Burgundy", "semanticDescription" => "Apalache Burgundy es un Culote largo térmico de gravel hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM3-W Polvareda", "semanticDescription" => "GM3-W Polvareda es un Maillot de gravel manga larga mujer para Mujer. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM3-W Bordala", "semanticDescription" => "GM3-W Bordala es un Maillot de gravel manga larga mujer para Mujer. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM3 Unbound", "semanticDescription" => "GM3 Unbound es un Maillot de gravel manga larga hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM3 Trailblaze", "semanticDescription" => "GM3 Trailblaze es un Maillot de gravel manga larga hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "M2 Morcuera", "semanticDescription" => "M2 Morcuera es un Maillot de manga corta hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Ezaro", "semanticDescription" => "M2 Ezaro es un Maillot de manga corta hombre para Hombre. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Susten", "semanticDescription" => "M2 Susten es un Maillot de manga corta hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Jouxplane", "semanticDescription" => "M2 Jouxplane es un Maillot de manga larga hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Falzarego", "semanticDescription" => "M2 Falzarego es un Maillot de manga larga hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "OS V1 Valiente Red", "semanticDescription" => "OS V1 Valiente Red es un Chaleco cortavientos hombre Club Atlético Osasuna x Siroko para Hombre. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "OS V1 Luchador Black", "semanticDescription" => "OS V1 Luchador Black es un Chaleco cortavientos hombre Club Atlético Osasuna x Siroko para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "OS BX Pro Luchador Black", "semanticDescription" => "OS BX Pro Luchador Black es un Culote corto hombre Club Atlético Osasuna x Siroko para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "OS BL Luchador White", "semanticDescription" => "OS BL Luchador White es un Camiseta interior hombre Club Atlético Osasuna x Siroko para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "OS S1 Valiente White", "semanticDescription" => "OS S1 Valiente White es un Calcetines ciclismo Club Atlético Osasuna x Siroko para unisex. Disponible en Blanco. Confeccionado en Poliamida, Poliéster, Elastano, Elastodieno."],
        ["name" => "OS S1 Valiente Red", "semanticDescription" => "OS S1 Valiente Red es un Calcetines ciclismo Club Atlético Osasuna x Siroko para unisex. Disponible en Rojo. Confeccionado en Poliamida, Elastodieno, Elastano."],
        ["name" => "OS NW Valiente Red", "semanticDescription" => "OS NW Valiente Red es un Braga ciclismo Club Atlético Osasuna x Siroko para unisex. Disponible en Rojo. Confeccionado en Poliéster."],
        ["name" => "OS RC Valiente Red", "semanticDescription" => "OS RC Valiente Red es un Gorra ciclismo Club Atlético Osasuna x Siroko para unisex. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "OS Hydro Valiente Red", "semanticDescription" => "OS Hydro Valiente Red es un Bidón ciclismo Club Atlético Osasuna x Siroko para unisex. Disponible en Rojo. Confeccionado en Polietileno, Polipropileno."],
        ["name" => "OS M2 Luchador Black", "semanticDescription" => "OS M2 Luchador Black es un Maillot M2 manga corta Osasuna para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX Silvretta-W", "semanticDescription" => "SRX Silvretta-W es un Maillot de manga corta ultraligero mujer para Mujer. Disponible en Rosa. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J1-W Bordala", "semanticDescription" => "J1-W Bordala es un Chaqueta softshell ciclismo mujer para Mujer. Disponible en Marrón. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J1 Lieja", "semanticDescription" => "J1 Lieja es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J1 Crostis", "semanticDescription" => "J1 Crostis es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J1 Naranco", "semanticDescription" => "J1 Naranco es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Beige. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S1 Brown", "semanticDescription" => "S1 Brown es un Calcetines para ciclismo para unisex. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "S1 Burgundy", "semanticDescription" => "S1 Burgundy es un Calcetines para ciclismo para unisex. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "V1 Hautacam", "semanticDescription" => "V1 Hautacam es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "V1 Cordal", "semanticDescription" => "V1 Cordal es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "V1 Klausen", "semanticDescription" => "V1 Klausen es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "BX Malga Palazzo", "semanticDescription" => "BX Malga Palazzo es un Culote largo ciclismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "Emberly Beige", "semanticDescription" => "Emberly Beige es un Sobrecamisa de gravel para verano mujer para Mujer. Disponible en Beige. Confeccionado en Poliamida, Elastano."],
        ["name" => "Stoneway Stone", "semanticDescription" => "Stoneway Stone es un Sobrecamisa de gravel para verano hombre para Hombre. Disponible en Blanco. Confeccionado en Poliamida, Elastano."],
        ["name" => "K-Core Nature Light Blue", "semanticDescription" => "K-Core Nature Light Blue es un Maillot ciclismo manga corta niño para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Pavi White", "semanticDescription" => "K-Core Pavi White es un Camiseta interior ciclismo niño para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Benji Black", "semanticDescription" => "K-Core Benji Black es un Culote corto ciclismo niño para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Playground Black", "semanticDescription" => "K-Core Playground Black es un Pantalones cortos ciclismo con badana niño para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "K-Core Chat White", "semanticDescription" => "K-Core Chat White es un Camiseta interior ciclismo niña para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Brisa Light Pink", "semanticDescription" => "K-Core Brisa Light Pink es un Maillot ciclismo manga corta niña para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Parkway Black", "semanticDescription" => "K-Core Parkway Black es un Culote corto ciclismo niña para Mujer. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "K-Core Racing Black", "semanticDescription" => "K-Core Racing Black es un Pantalones cortos ciclismo con badana niña para Mujer. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "K-Core Beartooth Black", "semanticDescription" => "K-Core Beartooth Black es un Guantes cortos de ciclismo niños para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "K-Core Roadrunner Black", "semanticDescription" => "K-Core Roadrunner Black es un Calcetines de ciclismo niños para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "S1 Blue Aqua", "semanticDescription" => "S1 Blue Aqua es un Calcetines para ciclismo para unisex. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM4 Strata Aubergine", "semanticDescription" => "GM4 Strata Aubergine es un Maillot de gravel sin mangas mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM4 Strata Light Yellow", "semanticDescription" => "GM4 Strata Light Yellow es un Maillot de gravel sin mangas mujer para Mujer. Disponible en Amarillo. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM2 Andina", "semanticDescription" => "GM2 Andina es un Maillot de gravel manga corta mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM2 Raíz", "semanticDescription" => "GM2 Raíz es un Maillot de gravel manga corta mujer para Mujer. Disponible en Beige. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM2 Forge", "semanticDescription" => "GM2 Forge es un Maillot de gravel manga corta hombre para Hombre. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM2 Gravitas", "semanticDescription" => "GM2 Gravitas es un Maillot de gravel manga corta hombre para Hombre. Disponible en Blanco, Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM5 Terraquest Brown", "semanticDescription" => "GM5 Terraquest Brown es un Maillot de gravel media cremallera hombre para Hombre. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM5 Terraquest Yellow", "semanticDescription" => "GM5 Terraquest Yellow es un Maillot de gravel media cremallera hombre para Hombre. Disponible en Amarillo. Confeccionado en Poliamida, Elastano."],
        ["name" => "Dust Aubergine", "semanticDescription" => "Dust Aubergine es un Culote corto gravel mujer para Mujer. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "Rugged Tile", "semanticDescription" => "Rugged Tile es un Culote corto gravel hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "Rugged Brown", "semanticDescription" => "Rugged Brown es un Culote corto gravel hombre para Hombre. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "Rockrover", "semanticDescription" => "Rockrover es un Camiseta de gravel hombre para Hombre. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "Core Cacti black", "semanticDescription" => "Core Cacti black es un Guantes cortos ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Corsa", "semanticDescription" => "M2 Corsa es un Maillot de manga larga hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Fly", "semanticDescription" => "M6R Fly es un Maillot ciclismo reciclado manga corta mujer para Mujer. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Pure", "semanticDescription" => "M6R Pure es un Maillot ciclismo reciclado manga corta mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Mercury", "semanticDescription" => "M6R Mercury es un Maillot ciclismo reciclado manga corta mujer para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Fresh", "semanticDescription" => "M6R Fresh es un Maillot ciclismo reciclado manga corta mujer para Mujer. Disponible en Turquesa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Vent", "semanticDescription" => "M6R Vent es un Maillot ciclismo reciclado manga corta hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Zero", "semanticDescription" => "M6R Zero es un Maillot ciclismo reciclado manga corta hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Apricot", "semanticDescription" => "M6R Apricot es un Maillot ciclismo reciclado manga corta hombre para Hombre. Disponible en Naranja. Confeccionado en Poliéster, Elastano."],
        ["name" => "M6R Filter", "semanticDescription" => "M6R Filter es un Maillot ciclismo reciclado manga corta hombre para Hombre. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Provence", "semanticDescription" => "M2 Provence es un Maillot de manga corta mujer para Mujer. Disponible en Blanco, Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Prix", "semanticDescription" => "M2 Prix es un Maillot de manga larga mujer para Mujer. Disponible en Turquesa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Venturi", "semanticDescription" => "M2 Venturi es un Maillot de manga corta mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Loud", "semanticDescription" => "M2 Loud es un Maillot de manga corta hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Luna", "semanticDescription" => "M8 Luna es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Syntony", "semanticDescription" => "M8 Syntony es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Route", "semanticDescription" => "M8 Route es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Habitat", "semanticDescription" => "M8 Habitat es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Torque", "semanticDescription" => "M8 Torque es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Environs", "semanticDescription" => "M8 Environs es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Inertia", "semanticDescription" => "M8 Inertia es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 Metre", "semanticDescription" => "M8 Metre es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "V1-W Lavaredo", "semanticDescription" => "V1-W Lavaredo es un Chaleco cortavientos ciclismo mujer para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "V1-W Berthel", "semanticDescription" => "V1-W Berthel es un Chaleco cortavientos ciclismo mujer para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX  Éland", "semanticDescription" => "SRX  Éland es un Maillot de manga corta ultraligero mujer para Mujer. Disponible en Verde. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "SRX  Vanguard", "semanticDescription" => "SRX  Vanguard es un Maillot de manga corta ultraligero mujer para Mujer. Disponible en Azul. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "SRX Senra", "semanticDescription" => "SRX Senra es un Maillot de manga corta ultraligero mujer para Mujer. Disponible en Rosa. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "SRX Pista", "semanticDescription" => "SRX Pista es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Rosa. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "V1 Lavaredo", "semanticDescription" => "V1 Lavaredo es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "V1 Berthel", "semanticDescription" => "V1 Berthel es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Cielo", "semanticDescription" => "M3 Cielo es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Noise", "semanticDescription" => "M2 Noise es un Maillot de manga larga hombre para Hombre. Disponible en Blanco, Rojo. Confeccionado en Elastano, Poliéster."],
        ["name" => "M2 Bora", "semanticDescription" => "M2 Bora es un Maillot de manga corta mujer para Mujer. Disponible en Verde, Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Nitro", "semanticDescription" => "M2 Nitro es un Maillot de manga corta hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Toscano", "semanticDescription" => "M2 Toscano es un Maillot de manga corta hombre para Hombre. Disponible en Coral. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Eclat", "semanticDescription" => "M3 Eclat es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Radiant", "semanticDescription" => "M3 Radiant es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Dawn", "semanticDescription" => "M3 Dawn es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Vista", "semanticDescription" => "M3 Vista es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Cadence", "semanticDescription" => "M3 Cadence es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Gris. Confeccionado en Poliéster, Elastano."],
        ["name" => "Cáucaso", "semanticDescription" => "Cáucaso es un Camiseta de gravel manga larga hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "DW Noord", "semanticDescription" => "DW Noord es un Zapatillas de ciclismo carretera invierno para unisex. Disponible en Negro. Confeccionado en Cuero sintético, Poliamida."],
        ["name" => "DW Shinobi", "semanticDescription" => "DW Shinobi es un Pasamontañas ciclismo invierno para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "DW Grotto", "semanticDescription" => "DW Grotto es un Maillot térmico ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "DW Keilir", "semanticDescription" => "DW Keilir es un Camiseta interior térmica ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Spruce", "semanticDescription" => "Spruce es un Camiseta de gravel manga larga hombre para Hombre. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "Rubra", "semanticDescription" => "Rubra es un Camiseta de gravel manga larga hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX II Vulture", "semanticDescription" => "SRX II Vulture es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX II Manila", "semanticDescription" => "SRX II Manila es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Blanco. Confeccionado en Poliamida, Elastano."],
        ["name" => "Mount Lemmon", "semanticDescription" => "Mount Lemmon es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "Malhao", "semanticDescription" => "Malhao es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "Basil", "semanticDescription" => "Basil es un Culote corto reciclado ciclismo hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano, Poliéster."],
        ["name" => "Thyme", "semanticDescription" => "Thyme es un Pantalón corto gravel hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Castleton", "semanticDescription" => "Castleton es un Culote corto gravel hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Poplar", "semanticDescription" => "Poplar es un Camiseta de gravel hombre para Hombre. Disponible en Verde. Confeccionado en Poliéster, Elastano."],
        ["name" => "Locust", "semanticDescription" => "Locust es un Camiseta de gravel hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "GM2 Wilder", "semanticDescription" => "GM2 Wilder es un Maillot de gravel manga corta hombre para Hombre. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "GM2 Tasmania", "semanticDescription" => "GM2 Tasmania es un Maillot de gravel manga corta hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "M2 Dash", "semanticDescription" => "M2 Dash es un Maillot de manga corta hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 Colmar", "semanticDescription" => "M3 Colmar es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "Emberly-W Blue", "semanticDescription" => "Emberly-W Blue es un Sobrecamisa de gravel para verano mujer para Mujer. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "Stoneway Red", "semanticDescription" => "Stoneway Red es un Sobrecamisa de gravel para verano hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "Classique Purple", "semanticDescription" => "Classique Purple es un Gorra retro ciclismo para unisex. Disponible en Morado. Confeccionado en Poliéster, Algodón."],
        ["name" => "Classique Black", "semanticDescription" => "Classique Black es un Gorra retro ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster, Algodón."],
        ["name" => "Offpath Red", "semanticDescription" => "Offpath Red es un Braga cuello ciclismo gravel para unisex. Disponible en Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "Offpath White", "semanticDescription" => "Offpath White es un Braga cuello ciclismo gravel para unisex. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 NRC Yellow", "semanticDescription" => "M8 NRC Yellow es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Amarillo. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8-W NRC Pink", "semanticDescription" => "M8-W NRC Pink es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8-W NRC Coral", "semanticDescription" => "M8-W NRC Coral es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Coral. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3-W NRC Blue", "semanticDescription" => "M3-W NRC Blue es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3-W NRC White", "semanticDescription" => "M3-W NRC White es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3-W NRC Purple", "semanticDescription" => "M3-W NRC Purple es un Maillot de manga corta mujer ultraligero para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "M3 NRC Blue", "semanticDescription" => "M3 NRC Blue es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX M4 Poggio", "semanticDescription" => "SRX M4 Poggio es un Maillot ciclismo térmico hombre para Hombre. Disponible en Gris. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX M4 Grupetto", "semanticDescription" => "SRX M4 Grupetto es un Maillot ciclismo térmico hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "M8 NRC Blue", "semanticDescription" => "M8 NRC Blue es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 NRC Purple", "semanticDescription" => "M8 NRC Purple es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8 NRC White", "semanticDescription" => "M8 NRC White es un Maillot ciclismo mesh manga corta hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8-W NRC White", "semanticDescription" => "M8-W NRC White es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M8-W NRC Blue", "semanticDescription" => "M8-W NRC Blue es un Maillot ciclismo mesh manga corta mujer para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "Chaser Blue", "semanticDescription" => "Chaser Blue es un Camiseta de gravel manga corta algodón hombre para Hombre. Disponible en Azul. Confeccionado en Algodón."],
        ["name" => "Chaser White", "semanticDescription" => "Chaser White es un Camiseta de gravel manga corta algodón hombre para Hombre. Disponible en Blanco. Confeccionado en Algodón."],
        ["name" => "Chaser-W Sand", "semanticDescription" => "Chaser-W Sand es un Camiseta de gravel manga corta algodón mujer para Mujer. Disponible en Beige. Confeccionado en Algodón."],
        ["name" => "Chaser-W Red", "semanticDescription" => "Chaser-W Red es un Camiseta de gravel manga corta algodón mujer para Mujer. Disponible en Rojo. Confeccionado en Algodón."],
        ["name" => "Lemur-W Red", "semanticDescription" => "Lemur-W Red es un Pantalón corto gravel mujer para Mujer. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "Block Red", "semanticDescription" => "Block Red es un Pantalón corto gravel hombre para Hombre. Disponible en Rojo. Confeccionado en Poliamida, Elastano."],
        ["name" => "Grace Light Green", "semanticDescription" => "Grace Light Green es un Chaqueta impermeable cicloturismo mujer para Mujer. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Uncharted Indigo", "semanticDescription" => "Uncharted Indigo es un Chaqueta impermeable cicloturismo hombre para Hombre. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "M3 NRC White", "semanticDescription" => "M3 NRC White es un Maillot de manga corta hombre ultraligero para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "SC V1 Idolo", "semanticDescription" => "SC V1 Idolo es un Chaleco cortavientos hombre Real Sporting de Gijón x Siroko para Hombre. Disponible en Blanco. Confeccionado en Poliéster."],
        ["name" => "SC V1 Ovación", "semanticDescription" => "SC V1 Ovación es un Chaleco cortavientos hombre Real Sporting de Gijón x Siroko para Hombre. Disponible en Beige, Negro. Confeccionado en Poliéster."],
        ["name" => "SC M2 Idolo", "semanticDescription" => "SC M2 Idolo es un Maillot de manga corta hombre Real Sporting de Gijón x Siroko para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "SC M2 Ovación", "semanticDescription" => "SC M2 Ovación es un Maillot de manga corta hombre Real Sporting de Gijón x Siroko para Hombre. Disponible en Beige, Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2-W NRC White", "semanticDescription" => "M2-W NRC White es un Maillot de manga corta mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 NRC Pink", "semanticDescription" => "M2 NRC Pink es un Maillot de manga corta hombre para Hombre. Disponible en Rosa. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2-W NRC Purple", "semanticDescription" => "M2-W NRC Purple es un Maillot de manga corta mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2-W NRC Lilac", "semanticDescription" => "M2-W NRC Lilac es un Maillot de manga corta mujer para Mujer. Disponible en Morado. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2-W NRC Blue", "semanticDescription" => "M2-W NRC Blue es un Maillot de manga corta mujer para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX SpeedMax", "semanticDescription" => "SRX SpeedMax es un Maillot de manga larga hombre ultraligero para Hombre. Disponible en Azul. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "S1 Fucsia Barillete", "semanticDescription" => "S1 Fucsia Barillete es un Calcetines para ciclismo para unisex. Disponible en Morado. Confeccionado en Poliamida, Elastano."],
        ["name" => "S1 Ochre Major", "semanticDescription" => "S1 Ochre Major es un Calcetines para ciclismo para unisex. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "DW Troms", "semanticDescription" => "DW Troms es un Culote largo ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "DW Territory", "semanticDescription" => "DW Territory es un Chaqueta softshell ciclismo invierno hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Denali", "semanticDescription" => "SRX Denali es un Camiseta interior cortavientos hombre para Hombre. Disponible en Negro. Confeccionado en Lana Merino, Poliamida."],
        ["name" => "Ultrablack", "semanticDescription" => "Ultrablack es un Camiseta interior ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "Clout", "semanticDescription" => "Clout es un Camiseta interior ciclismo hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "Brume", "semanticDescription" => "Brume es un Camiseta interior ciclismo hombre para Hombre. Disponible en Gris. Confeccionado en Poliéster, Elastano."],
        ["name" => "GS1 Black", "semanticDescription" => "GS1 Black es un Calcetines de gravel para unisex. Disponible en Negro, Gris. Confeccionado en Poliamida, Elastano."],
        ["name" => "Nimbus", "semanticDescription" => "Nimbus es un Perneras ciclismo verano para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "S1 Lilac Etna", "semanticDescription" => "S1 Lilac Etna es un Calcetines para ciclismo para unisex. Disponible en Lavanda. Confeccionado en Nailon, Elastano."],
        ["name" => "Block", "semanticDescription" => "Block es un Pantalón corto gravel hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "Valley", "semanticDescription" => "Valley es un Pantalón corto gravel hombre para Hombre. Disponible en Marrón, Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "Berg", "semanticDescription" => "Berg es un Culote corto gravel hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Rocket", "semanticDescription" => "Rocket es un Culote corto gravel hombre para Hombre. Disponible en Beige, Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "GS1 Mustard", "semanticDescription" => "GS1 Mustard es un Calcetines de gravel para unisex. Disponible en Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "Cedar", "semanticDescription" => "Cedar es un Camiseta de gravel hombre para Hombre. Disponible en Beige. Confeccionado en Poliéster, Elastano."],
        ["name" => "Tushar", "semanticDescription" => "Tushar es un Camiseta de gravel hombre para Hombre. Disponible en Arcilla, Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "Frontier", "semanticDescription" => "Frontier es un Guantes de gravel para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Maxim", "semanticDescription" => "SRX Maxim es un Culote corto ciclismo hombre para Hombre. Disponible en Gris, Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Bled", "semanticDescription" => "Bled es un Camiseta interior ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX Whirlwind", "semanticDescription" => "SRX Whirlwind es un Braga de lana ciclismo para unisex. Disponible en Negro. Confeccionado en Lana Merino."],
        ["name" => "SRX Ultra Warm-W", "semanticDescription" => "SRX Ultra Warm-W es un Chaleco térmico ciclismo mujer para Mujer. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "SRX Ultra Warm", "semanticDescription" => "SRX Ultra Warm es un Chaleco térmico ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Marin", "semanticDescription" => "Marin es un Cubrezapatillas de ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "Boulder", "semanticDescription" => "Boulder es un Punteras de ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "Vestkapp", "semanticDescription" => "Vestkapp es un Guantes de ciclismo para invierno para unisex. Disponible en Negro. Confeccionado en Poliéster."],
        ["name" => "S1 Gray Saas", "semanticDescription" => "S1 Gray Saas es un Calcetines para ciclismo para unisex. Disponible en Gris plata. Confeccionado en Nailon, Elastano."],
        ["name" => "SRX Borders", "semanticDescription" => "SRX Borders es un Manguitos SRX de ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J3 Seymour", "semanticDescription" => "J3 Seymour es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "J1 Khangai", "semanticDescription" => "J1 Khangai es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Caqui. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Nuremberg", "semanticDescription" => "Nuremberg es un Guantes de ciclismo para unisex. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX M4 Sandhill", "semanticDescription" => "SRX M4 Sandhill es un Maillot ciclismo térmico hombre para Hombre. Disponible en Beige, Marrón. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX Maloja", "semanticDescription" => "SRX Maloja es un Calcetines de ciclismo con lana merino para unisex. Disponible en Gris, Gris plata. Confeccionado en Lana Merino, Poliamida, Elastano."],
        ["name" => "SRX Grappa", "semanticDescription" => "SRX Grappa es un Calcetines de ciclismo con lana merino para unisex. Disponible en Negro, Gris. Confeccionado en Lana Merino, Poliamida, Elastano."],
        ["name" => "M2 Riemst", "semanticDescription" => "M2 Riemst es un Maillot de manga larga hombre para Hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Vezzana", "semanticDescription" => "M2 Vezzana es un Maillot de manga larga hombre para Hombre. Disponible en Azul, Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Triplet", "semanticDescription" => "M2 Triplet es un Maillot de manga larga hombre para Hombre. Disponible en Burdeos, Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX Rainfall", "semanticDescription" => "SRX Rainfall es un Perneras térmicas repelentes al agua para unisex. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "BX Fassa", "semanticDescription" => "BX Fassa es un Culote corto ciclismo hombre para Hombre. Disponible en Gris, Blanco. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "BX Umbrail", "semanticDescription" => "BX Umbrail es un Culote corto ciclismo hombre para Hombre. Disponible en Azul navy, Blanco. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "BX Oberwald", "semanticDescription" => "BX Oberwald es un Culote corto ciclismo hombre para Hombre. Disponible en Verde militar, Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "BX Bionaz", "semanticDescription" => "BX Bionaz es un Culote corto ciclismo hombre para Hombre. Disponible en Burdeos, Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "S1 Cyan Trollstigen", "semanticDescription" => "S1 Cyan Trollstigen es un Calcetines para ciclismo para unisex. Disponible en Cian. Confeccionado en Nailon, Elastano."],
        ["name" => "SRX M4 Volta", "semanticDescription" => "SRX M4 Volta es un Maillot ciclismo térmico hombre para Hombre. Disponible en Verde militar, Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "Forecast", "semanticDescription" => "Forecast es un Perneras térmicas ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX M4 Atlantis", "semanticDescription" => "SRX M4 Atlantis es un Maillot ciclismo térmico hombre para Hombre. Disponible en Amarillo neón, Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Aero Black", "semanticDescription" => "Aero Black es un Guantes ciclismo para unisex. Disponible en Negro. Confeccionado en Nailon, Poliuretano, Poliéster, Elastano."],
        ["name" => "J2 Tourmalet", "semanticDescription" => "J2 Tourmalet es un Chaquetas de lluvia ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliuretano."],
        ["name" => "SRX M4 Fleet Moss", "semanticDescription" => "SRX M4 Fleet Moss es un Maillot ciclismo térmico hombre para Hombre. Disponible en Negro, Gris. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX M4 Cubilla", "semanticDescription" => "SRX M4 Cubilla es un Maillot ciclismo térmico hombre para Hombre. Disponible en Azul navy, Azul eléctrico. Confeccionado en Poliamida, Elastano."],
        ["name" => "BX Envalira", "semanticDescription" => "BX Envalira es un Culote largo ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "BX Bolzano", "semanticDescription" => "BX Bolzano es un Culote largo ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "SRX Supreme", "semanticDescription" => "SRX Supreme es un Culote largo ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Black Sea", "semanticDescription" => "Black Sea es un Culote largo ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Flandrien", "semanticDescription" => "Flandrien es un Culote corto ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Essential Cap", "semanticDescription" => "Essential Cap es un Gorro térmico para ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "SRX Roselend", "semanticDescription" => "SRX Roselend es un Maillot de manga larga hombre ultraligero para Hombre. Disponible en Negro, Naranja intenso. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "Manguitos Climatik", "semanticDescription" => "Manguitos Climatik es un Manguitos ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "Braga cuello microfibra Climastar", "semanticDescription" => "Braga cuello microfibra Climastar es un Braga coolmax ciclismo para unisex. Disponible en Gris. Confeccionado en Poliamida, Elastano."],
        ["name" => "Ultra Polar", "semanticDescription" => "Ultra Polar es un Braga térmica ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Poliéster, Elastano."],
        ["name" => "Manguitos Térmicos ColdBlock", "semanticDescription" => "Manguitos Térmicos ColdBlock es un Manguitos ciclismo para unisex. Disponible en Negro. Confeccionado en Poliamida, Elastano."],
        ["name" => "J1 Furkapass", "semanticDescription" => "J1 Furkapass es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "J1 Ordino", "semanticDescription" => "J1 Ordino es un Chaqueta softshell ciclismo hombre para Hombre. Disponible en Verde militar. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "SRX Typhoon", "semanticDescription" => "SRX Typhoon es un Camiseta interior lana hombre para Hombre. Disponible en Negro. Confeccionado en Lana Merino."],
        ["name" => "SRX Black Ice", "semanticDescription" => "SRX Black Ice es un Camiseta interior lana hombre para Hombre. Disponible en Negro. Confeccionado en Lana Merino."],
        ["name" => "Velocity", "semanticDescription" => "Velocity es un camiseta interior ciclismo hombre para Hombre. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "Atomic", "semanticDescription" => "Atomic es un camiseta interior ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster, Elastano."],
        ["name" => "M2 Arizona", "semanticDescription" => "M2 Arizona es un Maillot de manga larga hombre para Hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster, Elastano."],
        ["name" => "SRX World Series", "semanticDescription" => "SRX World Series es un Culote corto ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "SRX Elite", "semanticDescription" => "SRX Elite es un Culote corto ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Nailon, Poliéster, Elastano."],
        ["name" => "V1 Blaast", "semanticDescription" => "V1 Blaast es un Chaleco cortavientos ciclismo hombre para Hombre. Disponible en Negro. Confeccionado en Poliéster."],
        ["name" => "SRX SpeedMax", "semanticDescription" => "SRX SpeedMax es un Maillot de manga larga hombre ultraligero para Hombre. Disponible en Azul. Confeccionado en Poliéster, Poliamida, Elastano."],
        ["name" => "Albulapass Light Blue", "semanticDescription" => "Albulapass Light Blue es un Calcetines retro para esquí para unisex. Disponible en Azul. Confeccionado en Algodón, Poliamida, Poliéster, Elastano."],
        ["name" => "Albulapass White", "semanticDescription" => "Albulapass White es un Calcetines retro para esquí para unisex. Disponible en Blanco. Confeccionado en Algodón, Poliamida, Poliéster, Elastano."],
        ["name" => "Fuji Brown", "semanticDescription" => "Fuji Brown es un Calcetines para snowboard para unisex. Disponible en Marrón. Confeccionado en Algodón, Poliéster, Poliamida, Elastano."],
        ["name" => "Fuji White", "semanticDescription" => "Fuji White es un Calcetines para snowboard para unisex. Disponible en Blanco. Confeccionado en Algodón, Poliéster, Poliamida, Elastano."],
        ["name" => "Fuji Olive Green", "semanticDescription" => "Fuji Olive Green es un Calcetines para snowboard para unisex. Disponible en Verde. Confeccionado en Algodón, Poliéster, Poliamida, Elastano."],
        ["name" => "Fuji Light Blue", "semanticDescription" => "Fuji Light Blue es un Calcetines para snowboard para unisex. Disponible en Azul. Confeccionado en Algodón, Poliamida, Poliéster, Elastano."],
        ["name" => "Player-W Green", "semanticDescription" => "Player-W Green es un Polo técnico media cremallera tenis mujer para Mujer. Disponible en Verde. Confeccionado en Poliamida, Elastano."],
        ["name" => "Player White", "semanticDescription" => "Player White es un Polo técnico media cremallera tenis hombre para Hombre. Disponible en Blanco. Confeccionado en Poliamida, Elastano."],
        ["name" => "Player Navy", "semanticDescription" => "Player Navy es un Polo técnico media cremallera tenis hombre para Hombre. Disponible en Azul. Confeccionado en Poliamida, Elastano."],
        ["name" => "Volley-W White", "semanticDescription" => "Volley-W White es un Pantalones acampanados tenis mujer para Mujer. Disponible en Blanco. Confeccionado en Poliéster, Elastano."],
        ["name" => "Volley-W Navy", "semanticDescription" => "Volley-W Navy es un Pantalones acampanados tenis mujer para Mujer. Disponible en Azul. Confeccionado en Poliéster, Elastano."],
    ];

    public function __construct(private readonly MessageBusInterface $commandBus)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $io->title('Seeding Siroko products');

        $created = 0;
        $indexed = 0;
        $errors = 0;

        foreach (self::PRODUCTS as $data) {
            try {
                $command = new CreateProductCommand($data['name'], $data['semanticDescription']);
                $this->commandBus->dispatch($command);
                ++$created;

                $this->commandBus->dispatch(new IndexProductCommand($command->id));
                ++$indexed;
            } catch (\Throwable $e) {
                ++$errors;
                $io->error(sprintf('[%s] %s', $data['name'], $e->getMessage()));
            }
        }

        $io->success(sprintf('Creados: %d | Indexados: %d | Errores: %d', $created, $indexed, $errors));

        return Command::SUCCESS;
    }
}
