<?php

declare(strict_types=1);

namespace App\Product\Infrastructure\Cli;

use App\Product\Application\CreateProduct\CreateProductCommand;
use App\Product\Application\IndexProduct\IndexProductCommand;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Messenger\MessageBusInterface;

#[AsCommand(
    name: 'app:seed:siroko-products',
    description: 'Seeds the database with Siroko cycling products and indexes them in Qdrant',
)]
final class SeedSirokoProductsCommand extends Command
{
    private const array PRODUCTS = [
        ['name' => 'SRX Ultra Warm Gray', 'semanticDescription' => 'Siroko SRX Ultra Warm Gray es un chaleco térmico ciclismo hombre para hombre. Disponible en Gris. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'SRX Premier-W Gray', 'semanticDescription' => 'Siroko SRX Premier-W Gray es un culote largo ciclismo mujer para mujer. Disponible en Gris. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'SRX Supreme Gray', 'semanticDescription' => 'Siroko SRX Supreme Gray es un culote largo ciclismo hombre para hombre. Disponible en Gris. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'Horizon Light Green', 'semanticDescription' => 'Siroko Horizon Light Green es una gorra resistente al agua cicloturismo para ciclistas. Disponible en Verde. Confeccionado en Poliamida.'],
        ['name' => 'Globe-trot Indigo', 'semanticDescription' => 'Siroko Globe-trot Indigo es una gorra resistente al agua cicloturismo para ciclistas. Disponible en Azul. Confeccionado en Poliamida.'],
        ['name' => 'Journey Light Green', 'semanticDescription' => 'Siroko Journey Light Green es una sudadera cicloturismo hombre para hombre. Disponible en Verde. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Soulful Sand', 'semanticDescription' => 'Siroko Soulful Sand es una sudadera cicloturismo mujer para mujer. Disponible en Beige, Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Embrace Orange', 'semanticDescription' => 'Siroko Embrace Orange es un bandana cicloturismo para mujer. Disponible en Naranja. Confeccionado en Algodón.'],
        ['name' => 'Shoall Light Green', 'semanticDescription' => 'Siroko Shoall Light Green es un bandana cicloturismo para hombre. Disponible en Verde. Confeccionado en Algodón.'],
        ['name' => 'Rush Black', 'semanticDescription' => 'Siroko Rush Black es una camiseta holgada manga corta cicloturismo hombre para hombre. Disponible en Negro. Confeccionado en Algodón.'],
        ['name' => 'Herb Green', 'semanticDescription' => 'Siroko Herb Green es una camiseta holgada manga corta cicloturismo hombre para hombre. Disponible en Verde. Confeccionado en Algodón.'],
        ['name' => 'Exploring Sand', 'semanticDescription' => 'Siroko Exploring Sand es una camiseta holgada manga corta cicloturismo hombre para hombre. Disponible en Beige. Confeccionado en Algodón.'],
        ['name' => 'Reef Light Green', 'semanticDescription' => 'Siroko Reef Light Green es una camiseta holgada manga corta cicloturismo mujer para mujer. Disponible en Verde. Confeccionado en Algodón.'],
        ['name' => 'Feel Sand', 'semanticDescription' => 'Siroko Feel Sand es una camiseta holgada manga corta cicloturismo mujer para mujer. Disponible en Beige. Confeccionado en Algodón.'],
        ['name' => 'Pilgrim Sand', 'semanticDescription' => 'Siroko Pilgrim Sand es una camiseta técnica manga corta cicloturismo hombre para hombre. Disponible en Beige. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Pilgrim Orange', 'semanticDescription' => 'Siroko Pilgrim Orange es una camiseta técnica manga corta cicloturismo hombre para hombre. Disponible en Naranja. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Map Purple', 'semanticDescription' => 'Siroko Map Purple es una camiseta técnica manga corta cicloturismo mujer para mujer. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Map Black', 'semanticDescription' => 'Siroko Map Black es una camiseta técnica manga corta cicloturismo mujer para mujer. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Daytrip Indigo', 'semanticDescription' => 'Siroko Daytrip Indigo es un pantalón corto cicloturismo hombre para hombre. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Daytrip Camel', 'semanticDescription' => 'Siroko Daytrip Camel es un pantalón corto cicloturismo hombre para hombre. Disponible en Beige. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Turf Gray Green', 'semanticDescription' => 'Siroko Turf Gray Green es un pantalón corto cicloturismo mujer para mujer. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Turf Purple', 'semanticDescription' => 'Siroko Turf Purple es un pantalón corto cicloturismo mujer para mujer. Disponible en Morado. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Tour Black', 'semanticDescription' => 'Siroko Tour Black es un culote corto sin tirantes cicloturismo hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'Roam Black', 'semanticDescription' => 'Siroko Roam Black es un culote corto sin tirantes cicloturismo mujer para mujer. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'ST1 Black', 'semanticDescription' => 'Siroko ST1 Black es un calcetines cicloturismo media caña para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'ST1 Green', 'semanticDescription' => 'Siroko ST1 Green es un calcetines cicloturismo media caña para ciclistas. Disponible en Verde. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Emberly Brown', 'semanticDescription' => 'Siroko Emberly Brown es un sobrecamisa de gravel para verano mujer para mujer. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Stoneway Black', 'semanticDescription' => 'Siroko Stoneway Black es un sobrecamisa de gravel para verano hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GS2 Green', 'semanticDescription' => 'Siroko GS2 Green es un calcetines caña media gravel para ciclistas. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GS2 Black', 'semanticDescription' => 'Siroko GS2 Black es un calcetines caña media gravel para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GS2 Blue', 'semanticDescription' => 'Siroko GS2 Blue es un calcetines caña media gravel para ciclistas. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GS2 Burgundy', 'semanticDescription' => 'Siroko GS2 Burgundy es un calcetines caña media gravel para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'S3 Blue', 'semanticDescription' => 'Siroko S3 Blue es un calcetines caña alta ciclismo invierno para ciclistas. Disponible en Azul. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'S3 Black', 'semanticDescription' => 'Siroko S3 Black es un calcetines caña alta ciclismo invierno para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'S3 Gray', 'semanticDescription' => 'Siroko S3 Gray es un calcetines caña alta ciclismo invierno para ciclistas. Disponible en Gris. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'S3 Purple', 'semanticDescription' => 'Siroko S3 Purple es un calcetines caña alta ciclismo invierno para ciclistas. Disponible en Morado. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'HE Cover Black', 'semanticDescription' => 'Siroko HE Cover Black es un funda impermeable casco ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster.'],
        ['name' => 'BX Colombier', 'semanticDescription' => 'Siroko BX Colombier es un culote corto reciclado ciclismo mujer para mujer. Disponible en Rosa. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'BX Semnoz', 'semanticDescription' => 'Siroko BX Semnoz es un culote corto reciclado ciclismo mujer para mujer. Disponible en Morado. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'BX Brocken', 'semanticDescription' => 'Siroko BX Brocken es un culote corto reciclado ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'BX Terres', 'semanticDescription' => 'Siroko BX Terres es un culote corto reciclado ciclismo hombre para hombre. Disponible en Marrón. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'SRX Fusion', 'semanticDescription' => 'Siroko SRX Fusion es un culote corto biodegradable ciclismo mujer para mujer. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'SRX Blend', 'semanticDescription' => 'Siroko SRX Blend es un culote corto biodegradable ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'MTB Slack Blue', 'semanticDescription' => 'Siroko MTB Slack Blue es una sudadera capucha mtb hombre para hombre. Disponible en Azul. Confeccionado en Algodón y Poliéster y Elastano.'],
        ['name' => 'MTB Slack Gray', 'semanticDescription' => 'Siroko MTB Slack Gray es una sudadera capucha mtb hombre para hombre. Disponible en Gris. Confeccionado en Algodón y Poliéster y Elastano.'],
        ['name' => 'J2 Nivolet', 'semanticDescription' => 'Siroko J2 Nivolet es un chaquetas de lluvia ciclismo hombre para hombre. Disponible en Azul. Confeccionado en Nailon y Poliuretano.'],
        ['name' => 'J2-W Zarza', 'semanticDescription' => 'Siroko J2-W Zarza es un chaquetas de lluvia ciclismo mujer para mujer. Disponible en Azul. Confeccionado en Nailon y Poliuretano.'],
        ['name' => 'Rutted-W Brown', 'semanticDescription' => 'Siroko Rutted-W Brown es una camiseta de gravel manga larga algodón mujer para mujer. Disponible en Marrón. Confeccionado en Algodón.'],
        ['name' => 'Rutted Green', 'semanticDescription' => 'Siroko Rutted Green es una camiseta de gravel manga larga algodón hombre para hombre. Disponible en Verde. Confeccionado en Algodón.'],
        ['name' => 'Rutted Burgundy', 'semanticDescription' => 'Siroko Rutted Burgundy es una camiseta de gravel manga larga algodón hombre para hombre. Disponible en Rojo. Confeccionado en Algodón.'],
        ['name' => 'SRX Sella', 'semanticDescription' => 'Siroko SRX Sella es un calcetines de ciclismo con lana merino para ciclistas. Disponible en Rosa. Confeccionado en Poliamida y Lana Merino y Poliéster y Acrílico y Elastano.'],
        ['name' => 'GS1 Lilac', 'semanticDescription' => 'Siroko GS1 Lilac es un calcetines de gravel para ciclistas. Disponible en Morado. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'GS1 Light Yellow', 'semanticDescription' => 'Siroko GS1 Light Yellow es un calcetines de gravel para ciclistas. Disponible en Amarillo. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'GS1 Tile', 'semanticDescription' => 'Siroko GS1 Tile es un calcetines de gravel para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'GS1 Yellow', 'semanticDescription' => 'Siroko GS1 Yellow es un calcetines de gravel para ciclistas. Disponible en Amarillo. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Capst Green', 'semanticDescription' => 'Siroko Capst Green es una gorra de gravel para ciclistas. Disponible en Verde. Confeccionado en Poliéster.'],
        ['name' => 'Spugla-W', 'semanticDescription' => 'Siroko Spugla-W es una camiseta de gravel mujer para ciclistas. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'HB Thermal Black', 'semanticDescription' => 'Siroko HB Thermal Black es un cinta orejera ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'HB Thermal Burgundy', 'semanticDescription' => 'Siroko HB Thermal Burgundy es un cinta orejera ciclismo para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J3 Souplesse', 'semanticDescription' => 'Siroko J3 Souplesse es una chaqueta softshell ciclismo hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'SRX Aravis', 'semanticDescription' => 'Siroko SRX Aravis es un calcetines de ciclismo con lana merino para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Lana Merino y Poliéster y Acrílico y Elastano.'],
        ['name' => 'M9-W Scanuppia Brown', 'semanticDescription' => 'Siroko M9-W Scanuppia Brown es un maillot ciclismo manga larga sin cremallera mujer para mujer. Disponible en Marrón. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'M9-W Scanuppia Purple', 'semanticDescription' => 'Siroko M9-W Scanuppia Purple es un maillot ciclismo manga larga sin cremallera mujer para mujer. Disponible en Morado. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'NW Shield Black', 'semanticDescription' => 'Siroko NW Shield Black es un braga cuello ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida.'],
        ['name' => 'NW Shield Burgundy', 'semanticDescription' => 'Siroko NW Shield Burgundy es un braga cuello ciclismo para ciclistas. Disponible en Rojo. Confeccionado en Poliamida.'],
        ['name' => 'GM6 Rideout Green', 'semanticDescription' => 'Siroko GM6 Rideout Green es un maillot de gravel manga larga hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM6 Rideout Black', 'semanticDescription' => 'Siroko GM6 Rideout Black es un maillot de gravel manga larga hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'DW Valdres Black', 'semanticDescription' => 'Siroko DW Valdres Black es un maillot térmico capucha ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'DW Finestre Black', 'semanticDescription' => 'Siroko DW Finestre Black es una camiseta interior térmica capucha ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'M9 Scanuppia Black', 'semanticDescription' => 'Siroko M9 Scanuppia Black es un maillot ciclismo manga larga sin cremallera hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'M9 Scanuppia Beige', 'semanticDescription' => 'Siroko M9 Scanuppia Beige es un maillot ciclismo manga larga sin cremallera hombre para hombre. Disponible en Beige. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Apalache Burgundy', 'semanticDescription' => 'Siroko Apalache Burgundy es un culote largo térmico de gravel hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM3-W Polvareda', 'semanticDescription' => 'Siroko GM3-W Polvareda es un maillot de gravel manga larga mujer para mujer. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM3-W Bordala', 'semanticDescription' => 'Siroko GM3-W Bordala es un maillot de gravel manga larga mujer para mujer. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM3 Unbound', 'semanticDescription' => 'Siroko GM3 Unbound es un maillot de gravel manga larga hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM3 Trailblaze', 'semanticDescription' => 'Siroko GM3 Trailblaze es un maillot de gravel manga larga hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'M2 Morcuera', 'semanticDescription' => 'Siroko M2 Morcuera es un maillot de manga corta hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Ezaro', 'semanticDescription' => 'Siroko M2 Ezaro es un maillot de manga corta hombre para hombre. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Susten', 'semanticDescription' => 'Siroko M2 Susten es un maillot de manga corta hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Jouxplane', 'semanticDescription' => 'Siroko M2 Jouxplane es un maillot de manga larga hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Falzarego', 'semanticDescription' => 'Siroko M2 Falzarego es un maillot de manga larga hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'OS V1 Valiente Red', 'semanticDescription' => 'Siroko OS V1 Valiente Red es un chaleco cortavientos hombre club atlético osasuna x siroko para hombre. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'OS V1 Luchador Black', 'semanticDescription' => 'Siroko OS V1 Luchador Black es un chaleco cortavientos hombre club atlético osasuna x siroko para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'OS BX Pro Luchador Black', 'semanticDescription' => 'Siroko OS BX Pro Luchador Black es un culote corto hombre club atlético osasuna x siroko para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'OS BL Luchador White', 'semanticDescription' => 'Siroko OS BL Luchador White es una camiseta interior hombre club atlético osasuna x siroko para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'OS S1 Valiente White', 'semanticDescription' => 'Siroko OS S1 Valiente White es un calcetines ciclismo club atlético osasuna x siroko para ciclistas. Disponible en Blanco. Confeccionado en Poliamida y Poliéster y Elastano y Elastodieno.'],
        ['name' => 'OS S1 Valiente Red', 'semanticDescription' => 'Siroko OS S1 Valiente Red es un calcetines ciclismo club atlético osasuna x siroko para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Elastodieno y Elastano.'],
        ['name' => 'OS NW Valiente Red', 'semanticDescription' => 'Siroko OS NW Valiente Red es un braga ciclismo club atlético osasuna x siroko para ciclistas. Disponible en Rojo. Confeccionado en Poliéster.'],
        ['name' => 'OS RC Valiente Red', 'semanticDescription' => 'Siroko OS RC Valiente Red es una gorra ciclismo club atlético osasuna x siroko para ciclistas. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'OS Hydro Valiente Red', 'semanticDescription' => 'Siroko OS Hydro Valiente Red es un bidón ciclismo club atlético osasuna x siroko para ciclistas. Disponible en Rojo. Confeccionado en Polietileno y Polipropileno.'],
        ['name' => 'OS M2 Luchador Black', 'semanticDescription' => 'Siroko OS M2 Luchador Black es un maillot m2 manga corta osasuna para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX Silvretta-W', 'semanticDescription' => 'Siroko SRX Silvretta-W es un maillot de manga corta ultraligero mujer para mujer. Disponible en Rosa. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J1-W Bordala', 'semanticDescription' => 'Siroko J1-W Bordala es una chaqueta softshell ciclismo mujer para mujer. Disponible en Marrón. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J1 Lieja', 'semanticDescription' => 'Siroko J1 Lieja es una chaqueta softshell ciclismo hombre para hombre. Disponible en Azul. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J1 Crostis', 'semanticDescription' => 'Siroko J1 Crostis es una chaqueta softshell ciclismo hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J1 Naranco', 'semanticDescription' => 'Siroko J1 Naranco es una chaqueta softshell ciclismo hombre para hombre. Disponible en Beige. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'S1 Brown', 'semanticDescription' => 'Siroko S1 Brown es un calcetines para ciclismo para ciclistas. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'S1 Burgundy', 'semanticDescription' => 'Siroko S1 Burgundy es un calcetines para ciclismo para ciclistas. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'V1 Hautacam', 'semanticDescription' => 'Siroko V1 Hautacam es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1 Cordal', 'semanticDescription' => 'Siroko V1 Cordal es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1 Klausen', 'semanticDescription' => 'Siroko V1 Klausen es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'BX Malga Palazzo', 'semanticDescription' => 'Siroko BX Malga Palazzo es un culote largo ciclismo hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'Emberly Beige', 'semanticDescription' => 'Siroko Emberly Beige es un sobrecamisa de gravel para verano mujer para mujer. Disponible en Beige. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Stoneway Stone', 'semanticDescription' => 'Siroko Stoneway Stone es un sobrecamisa de gravel para verano hombre para hombre. Disponible en Blanco. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'K-Core Nature Light Blue', 'semanticDescription' => 'Siroko K-Core Nature Light Blue es un maillot ciclismo manga corta niño para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Pavi White', 'semanticDescription' => 'Siroko K-Core Pavi White es una camiseta interior ciclismo niño para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Benji Black', 'semanticDescription' => 'Siroko K-Core Benji Black es un culote corto ciclismo niño para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Playground Black', 'semanticDescription' => 'Siroko K-Core Playground Black es un pantalones cortos ciclismo con badana niño para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'K-Core Chat White', 'semanticDescription' => 'Siroko K-Core Chat White es una camiseta interior ciclismo niña para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Brisa Light Pink', 'semanticDescription' => 'Siroko K-Core Brisa Light Pink es un maillot ciclismo manga corta niña para mujer. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Parkway Black', 'semanticDescription' => 'Siroko K-Core Parkway Black es un culote corto ciclismo niña para mujer. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'K-Core Racing Black', 'semanticDescription' => 'Siroko K-Core Racing Black es un pantalones cortos ciclismo con badana niña para mujer. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'K-Core Beartooth Black', 'semanticDescription' => 'Siroko K-Core Beartooth Black es un guantes cortos de ciclismo niños para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'K-Core Roadrunner Black', 'semanticDescription' => 'Siroko K-Core Roadrunner Black es un calcetines de ciclismo niños para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'S1 Blue Aqua', 'semanticDescription' => 'Siroko S1 Blue Aqua es un calcetines para ciclismo para ciclistas. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM4 Strata Aubergine', 'semanticDescription' => 'Siroko GM4 Strata Aubergine es un maillot de gravel sin mangas mujer para mujer. Disponible en Morado. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM4 Strata Light Yellow', 'semanticDescription' => 'Siroko GM4 Strata Light Yellow es un maillot de gravel sin mangas mujer para mujer. Disponible en Amarillo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM2 Andina', 'semanticDescription' => 'Siroko GM2 Andina es un maillot de gravel manga corta mujer para mujer. Disponible en Morado. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM2 Raíz', 'semanticDescription' => 'Siroko GM2 Raíz es un maillot de gravel manga corta mujer para mujer. Disponible en Beige. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM2 Forge', 'semanticDescription' => 'Siroko GM2 Forge es un maillot de gravel manga corta hombre para hombre. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM2 Gravitas', 'semanticDescription' => 'Siroko GM2 Gravitas es un maillot de gravel manga corta hombre para hombre. Disponible en Blanco, Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM5 Terraquest Brown', 'semanticDescription' => 'Siroko GM5 Terraquest Brown es un maillot de gravel media cremallera hombre para hombre. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM5 Terraquest Yellow', 'semanticDescription' => 'Siroko GM5 Terraquest Yellow es un maillot de gravel media cremallera hombre para hombre. Disponible en Amarillo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Dust Aubergine', 'semanticDescription' => 'Siroko Dust Aubergine es un culote corto gravel mujer para mujer. Disponible en Morado. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Rugged Tile', 'semanticDescription' => 'Siroko Rugged Tile es un culote corto gravel hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Rugged Brown', 'semanticDescription' => 'Siroko Rugged Brown es un culote corto gravel hombre para hombre. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Rockrover', 'semanticDescription' => 'Siroko Rockrover es una camiseta de gravel hombre para hombre. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Core Cacti black', 'semanticDescription' => 'Siroko Core Cacti black es un guantes cortos ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Corsa', 'semanticDescription' => 'Siroko M2 Corsa es un maillot de manga larga hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Fly', 'semanticDescription' => 'Siroko M6R Fly es un maillot ciclismo reciclado manga corta mujer para mujer. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Pure', 'semanticDescription' => 'Siroko M6R Pure es un maillot ciclismo reciclado manga corta mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Mercury', 'semanticDescription' => 'Siroko M6R Mercury es un maillot ciclismo reciclado manga corta mujer para mujer. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Fresh', 'semanticDescription' => 'Siroko M6R Fresh es un maillot ciclismo reciclado manga corta mujer para mujer. Disponible en Turquesa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Vent', 'semanticDescription' => 'Siroko M6R Vent es un maillot ciclismo reciclado manga corta hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Zero', 'semanticDescription' => 'Siroko M6R Zero es un maillot ciclismo reciclado manga corta hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Apricot', 'semanticDescription' => 'Siroko M6R Apricot es un maillot ciclismo reciclado manga corta hombre para hombre. Disponible en Naranja. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M6R Filter', 'semanticDescription' => 'Siroko M6R Filter es un maillot ciclismo reciclado manga corta hombre para hombre. Disponible en Verde. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Provence', 'semanticDescription' => 'Siroko M2 Provence es un maillot de manga corta mujer para mujer. Disponible en Blanco, Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Prix', 'semanticDescription' => 'Siroko M2 Prix es un maillot de manga larga mujer para mujer. Disponible en Turquesa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Venturi', 'semanticDescription' => 'Siroko M2 Venturi es un maillot de manga corta mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Loud', 'semanticDescription' => 'Siroko M2 Loud es un maillot de manga corta hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Luna', 'semanticDescription' => 'Siroko M8 Luna es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Syntony', 'semanticDescription' => 'Siroko M8 Syntony es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Verde. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Route', 'semanticDescription' => 'Siroko M8 Route es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Habitat', 'semanticDescription' => 'Siroko M8 Habitat es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Torque', 'semanticDescription' => 'Siroko M8 Torque es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Environs', 'semanticDescription' => 'Siroko M8 Environs es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Inertia', 'semanticDescription' => 'Siroko M8 Inertia es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 Metre', 'semanticDescription' => 'Siroko M8 Metre es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1-W Lavaredo', 'semanticDescription' => 'Siroko V1-W Lavaredo es un chaleco cortavientos ciclismo mujer para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1-W Berthel', 'semanticDescription' => 'Siroko V1-W Berthel es un chaleco cortavientos ciclismo mujer para mujer. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX  Éland', 'semanticDescription' => 'Siroko SRX  Éland es un maillot de manga corta ultraligero mujer para mujer. Disponible en Verde. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'SRX  Vanguard', 'semanticDescription' => 'Siroko SRX  Vanguard es un maillot de manga corta ultraligero mujer para mujer. Disponible en Azul. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'SRX Senra', 'semanticDescription' => 'Siroko SRX Senra es un maillot de manga corta ultraligero mujer para mujer. Disponible en Rosa. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'SRX Pista', 'semanticDescription' => 'Siroko SRX Pista es un maillot de manga corta hombre ultraligero para hombre. Disponible en Rosa. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'V1 Lavaredo', 'semanticDescription' => 'Siroko V1 Lavaredo es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1 Berthel', 'semanticDescription' => 'Siroko V1 Berthel es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Cielo', 'semanticDescription' => 'Siroko M3 Cielo es un maillot de manga corta mujer ultraligero para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Noise', 'semanticDescription' => 'Siroko M2 Noise es un maillot de manga larga hombre para hombre. Disponible en Blanco, Rojo. Confeccionado en Elastano y Poliéster.'],
        ['name' => 'M2 Bora', 'semanticDescription' => 'Siroko M2 Bora es un maillot de manga corta mujer para mujer. Disponible en Verde, Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Nitro', 'semanticDescription' => 'Siroko M2 Nitro es un maillot de manga corta hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Toscano', 'semanticDescription' => 'Siroko M2 Toscano es un maillot de manga corta hombre para hombre. Disponible en Coral. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Eclat', 'semanticDescription' => 'Siroko M3 Eclat es un maillot de manga corta mujer ultraligero para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Radiant', 'semanticDescription' => 'Siroko M3 Radiant es un maillot de manga corta mujer ultraligero para mujer. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Dawn', 'semanticDescription' => 'Siroko M3 Dawn es un maillot de manga corta hombre ultraligero para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Vista', 'semanticDescription' => 'Siroko M3 Vista es un maillot de manga corta hombre ultraligero para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Cadence', 'semanticDescription' => 'Siroko M3 Cadence es un maillot de manga corta hombre ultraligero para hombre. Disponible en Gris. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Cáucaso', 'semanticDescription' => 'Siroko Cáucaso es una camiseta de gravel manga larga hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'DW Noord', 'semanticDescription' => 'Siroko DW Noord es un zapatillas de ciclismo carretera invierno para ciclistas. Disponible en Negro. Confeccionado en Cuero sintético y Poliamida.'],
        ['name' => 'DW Shinobi', 'semanticDescription' => 'Siroko DW Shinobi es un pasamontañas ciclismo invierno para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'DW Grotto', 'semanticDescription' => 'Siroko DW Grotto es un maillot térmico ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'DW Keilir', 'semanticDescription' => 'Siroko DW Keilir es una camiseta interior térmica ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Spruce', 'semanticDescription' => 'Siroko Spruce es una camiseta de gravel manga larga hombre para hombre. Disponible en Verde. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Rubra', 'semanticDescription' => 'Siroko Rubra es una camiseta de gravel manga larga hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX II Vulture', 'semanticDescription' => 'Siroko SRX II Vulture es un maillot de manga corta hombre ultraligero para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX II Manila', 'semanticDescription' => 'Siroko SRX II Manila es un maillot de manga corta hombre ultraligero para hombre. Disponible en Blanco. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Mount Lemmon', 'semanticDescription' => 'Siroko Mount Lemmon es un culote corto reciclado ciclismo hombre para hombre. Disponible en Gris. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'Malhao', 'semanticDescription' => 'Siroko Malhao es un culote corto reciclado ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'Basil', 'semanticDescription' => 'Siroko Basil es un culote corto reciclado ciclismo hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano y Poliéster.'],
        ['name' => 'Thyme', 'semanticDescription' => 'Siroko Thyme es un pantalón corto gravel hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Castleton', 'semanticDescription' => 'Siroko Castleton es un culote corto gravel hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Poplar', 'semanticDescription' => 'Siroko Poplar es una camiseta de gravel hombre para hombre. Disponible en Verde. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Locust', 'semanticDescription' => 'Siroko Locust es una camiseta de gravel hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'GM2 Wilder', 'semanticDescription' => 'Siroko GM2 Wilder es un maillot de gravel manga corta hombre para hombre. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'GM2 Tasmania', 'semanticDescription' => 'Siroko GM2 Tasmania es un maillot de gravel manga corta hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'M2 Dash', 'semanticDescription' => 'Siroko M2 Dash es un maillot de manga corta hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Colmar', 'semanticDescription' => 'Siroko M3 Colmar es un maillot de manga corta mujer ultraligero para mujer. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Emberly-W Blue', 'semanticDescription' => 'Siroko Emberly-W Blue es un sobrecamisa de gravel para verano mujer para mujer. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Stoneway Red', 'semanticDescription' => 'Siroko Stoneway Red es un sobrecamisa de gravel para verano hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Classique Purple', 'semanticDescription' => 'Siroko Classique Purple es una gorra retro ciclismo para ciclistas. Disponible en Morado. Confeccionado en Poliéster y Algodón.'],
        ['name' => 'Classique Black', 'semanticDescription' => 'Siroko Classique Black es una gorra retro ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster y Algodón.'],
        ['name' => 'Offpath Red', 'semanticDescription' => 'Siroko Offpath Red es un braga cuello ciclismo gravel para ciclistas. Disponible en Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Offpath White', 'semanticDescription' => 'Siroko Offpath White es un braga cuello ciclismo gravel para ciclistas. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 NRC Yellow', 'semanticDescription' => 'Siroko M8 NRC Yellow es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Amarillo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8-W NRC Pink', 'semanticDescription' => 'Siroko M8-W NRC Pink es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8-W NRC Coral', 'semanticDescription' => 'Siroko M8-W NRC Coral es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Coral. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3-W NRC Blue', 'semanticDescription' => 'Siroko M3-W NRC Blue es un maillot de manga corta mujer ultraligero para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3-W NRC White', 'semanticDescription' => 'Siroko M3-W NRC White es un maillot de manga corta mujer ultraligero para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3-W NRC Purple', 'semanticDescription' => 'Siroko M3-W NRC Purple es un maillot de manga corta mujer ultraligero para mujer. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 NRC Blue', 'semanticDescription' => 'Siroko M3 NRC Blue es un maillot de manga corta hombre ultraligero para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX M4 Poggio', 'semanticDescription' => 'Siroko SRX M4 Poggio es un maillot ciclismo térmico hombre para hombre. Disponible en Gris. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX M4 Grupetto', 'semanticDescription' => 'Siroko SRX M4 Grupetto es un maillot ciclismo térmico hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'M8 NRC Blue', 'semanticDescription' => 'Siroko M8 NRC Blue es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 NRC Purple', 'semanticDescription' => 'Siroko M8 NRC Purple es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8 NRC White', 'semanticDescription' => 'Siroko M8 NRC White es un maillot ciclismo mesh manga corta hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8-W NRC White', 'semanticDescription' => 'Siroko M8-W NRC White es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M8-W NRC Blue', 'semanticDescription' => 'Siroko M8-W NRC Blue es un maillot ciclismo mesh manga corta mujer para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Chaser Blue', 'semanticDescription' => 'Siroko Chaser Blue es una camiseta de gravel manga corta algodón hombre para hombre. Disponible en Azul. Confeccionado en Algodón.'],
        ['name' => 'Chaser White', 'semanticDescription' => 'Siroko Chaser White es una camiseta de gravel manga corta algodón hombre para hombre. Disponible en Blanco. Confeccionado en Algodón.'],
        ['name' => 'Chaser-W Sand', 'semanticDescription' => 'Siroko Chaser-W Sand es una camiseta de gravel manga corta algodón mujer para mujer. Disponible en Beige. Confeccionado en Algodón.'],
        ['name' => 'Chaser-W Red', 'semanticDescription' => 'Siroko Chaser-W Red es una camiseta de gravel manga corta algodón mujer para mujer. Disponible en Rojo. Confeccionado en Algodón.'],
        ['name' => 'Lemur-W Red', 'semanticDescription' => 'Siroko Lemur-W Red es un pantalón corto gravel mujer para mujer. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Block Red', 'semanticDescription' => 'Siroko Block Red es un pantalón corto gravel hombre para hombre. Disponible en Rojo. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Grace Light Green', 'semanticDescription' => 'Siroko Grace Light Green es una chaqueta impermeable cicloturismo mujer para mujer. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Uncharted Indigo', 'semanticDescription' => 'Siroko Uncharted Indigo es una chaqueta impermeable cicloturismo hombre para hombre. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'M3 NRC White', 'semanticDescription' => 'Siroko M3 NRC White es un maillot de manga corta hombre ultraligero para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SC V1 Idolo', 'semanticDescription' => 'Siroko SC V1 Idolo es un chaleco cortavientos hombre real sporting de gijón x siroko para hombre. Disponible en Blanco. Confeccionado en Poliéster.'],
        ['name' => 'SC V1 Ovación', 'semanticDescription' => 'Siroko SC V1 Ovación es un chaleco cortavientos hombre real sporting de gijón x siroko para hombre. Disponible en Beige, Negro. Confeccionado en Poliéster.'],
        ['name' => 'SC M2 Idolo', 'semanticDescription' => 'Siroko SC M2 Idolo es un maillot de manga corta hombre real sporting de gijón x siroko para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SC M2 Ovación', 'semanticDescription' => 'Siroko SC M2 Ovación es un maillot de manga corta hombre real sporting de gijón x siroko para hombre. Disponible en Beige, Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2-W NRC White', 'semanticDescription' => 'Siroko M2-W NRC White es un maillot de manga corta mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 NRC Pink', 'semanticDescription' => 'Siroko M2 NRC Pink es un maillot de manga corta hombre para hombre. Disponible en Rosa. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 NRC Black', 'semanticDescription' => 'Siroko M2 NRC Black es un maillot de manga corta hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2-W NRC Purple', 'semanticDescription' => 'Siroko M2-W NRC Purple es un maillot de manga corta mujer para mujer. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2-W NRC Lilac', 'semanticDescription' => 'Siroko M2-W NRC Lilac es un maillot de manga corta mujer para mujer. Disponible en Morado. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2-W NRC Blue', 'semanticDescription' => 'Siroko M2-W NRC Blue es un maillot de manga corta mujer para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'DW Troms', 'semanticDescription' => 'Siroko DW Troms es un culote largo ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'DW Territory', 'semanticDescription' => 'Siroko DW Territory es una chaqueta softshell ciclismo invierno hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'SRX Denali', 'semanticDescription' => 'Siroko SRX Denali es una camiseta interior cortavientos hombre para hombre. Disponible en Negro. Confeccionado en Lana Merino y Poliamida.'],
        ['name' => 'M3 Mustair', 'semanticDescription' => 'Siroko M3 Mustair es un maillot de manga corta hombre ultraligero para hombre. Disponible en Verde ceniza, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Swift', 'semanticDescription' => 'Siroko M3 Swift es un maillot de manga corta hombre ultraligero para hombre. Disponible en Beige, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Moors', 'semanticDescription' => 'Siroko M2 Moors es un maillot de manga corta hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Granfondo', 'semanticDescription' => 'Siroko M2 Granfondo es un maillot de manga corta hombre para hombre. Disponible en Blanco, Gris. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Ultrablack', 'semanticDescription' => 'Siroko Ultrablack es una camiseta interior ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Clout', 'semanticDescription' => 'Siroko Clout es una camiseta interior ciclismo hombre para hombre. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Brume', 'semanticDescription' => 'Siroko Brume es una camiseta interior ciclismo hombre para hombre. Disponible en Gris. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'GS1 Black', 'semanticDescription' => 'Siroko GS1 Black es un calcetines de gravel para ciclistas. Disponible en Negro, Gris. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Nimbus', 'semanticDescription' => 'Siroko Nimbus es un perneras ciclismo verano para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'S1 Lilac Etna', 'semanticDescription' => 'Siroko S1 Lilac Etna es un calcetines para ciclismo para ciclistas. Disponible en Lavanda. Confeccionado en Nailon y Elastano.'],
        ['name' => 'Block', 'semanticDescription' => 'Siroko Block es un pantalón corto gravel hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Valley', 'semanticDescription' => 'Siroko Valley es un pantalón corto gravel hombre para hombre. Disponible en Marrón, Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Berg', 'semanticDescription' => 'Siroko Berg es un culote corto gravel hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Rocket', 'semanticDescription' => 'Siroko Rocket es un culote corto gravel hombre para hombre. Disponible en Beige, Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'GS1 Mustard', 'semanticDescription' => 'Siroko GS1 Mustard es un calcetines de gravel para ciclistas. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Cedar', 'semanticDescription' => 'Siroko Cedar es una camiseta de gravel hombre para hombre. Disponible en Beige. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Tushar', 'semanticDescription' => 'Siroko Tushar es una camiseta de gravel hombre para hombre. Disponible en Arcilla, Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Frontier', 'semanticDescription' => 'Siroko Frontier es un guantes de gravel para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'SRX Maxim', 'semanticDescription' => 'Siroko SRX Maxim es un culote corto ciclismo hombre para hombre. Disponible en Gris, Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Bled', 'semanticDescription' => 'Siroko Bled es una camiseta interior ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX Whirlwind', 'semanticDescription' => 'Siroko SRX Whirlwind es un braga de lana ciclismo para ciclistas. Disponible en Negro. Confeccionado en Lana Merino.'],
        ['name' => 'SRX Ultra Warm-W', 'semanticDescription' => 'Siroko SRX Ultra Warm-W es un chaleco térmico ciclismo mujer para mujer. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'SRX Ultra Warm', 'semanticDescription' => 'Siroko SRX Ultra Warm es un chaleco térmico ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Marin', 'semanticDescription' => 'Siroko Marin es un cubrezapatillas de ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Boulder', 'semanticDescription' => 'Siroko Boulder es un punteras de ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'Vestkapp', 'semanticDescription' => 'Siroko Vestkapp es un guantes de ciclismo para invierno para ciclistas. Disponible en Negro. Confeccionado en Poliéster.'],
        ['name' => 'S1 Gray Saas', 'semanticDescription' => 'Siroko S1 Gray Saas es un calcetines para ciclismo para ciclistas. Disponible en Gris plata. Confeccionado en Nailon y Elastano.'],
        ['name' => 'SRX Borders', 'semanticDescription' => 'Siroko SRX Borders es un manguitos srx de ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J3 Seymour', 'semanticDescription' => 'Siroko J3 Seymour es una chaqueta softshell ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'J1 Khangai', 'semanticDescription' => 'Siroko J1 Khangai es una chaqueta softshell ciclismo hombre para hombre. Disponible en Caqui. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Nuremberg', 'semanticDescription' => 'Siroko Nuremberg es un guantes de ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX M4 Sandhill', 'semanticDescription' => 'Siroko SRX M4 Sandhill es un maillot ciclismo térmico hombre para hombre. Disponible en Beige, Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX Maloja', 'semanticDescription' => 'Siroko SRX Maloja es un calcetines de ciclismo con lana merino para ciclistas. Disponible en Gris, Gris plata. Confeccionado en Lana Merino y Poliamida y Elastano.'],
        ['name' => 'SRX Grappa', 'semanticDescription' => 'Siroko SRX Grappa es un calcetines de ciclismo con lana merino para ciclistas. Disponible en Negro, Gris. Confeccionado en Lana Merino y Poliamida y Elastano.'],
        ['name' => 'M2 Riemst', 'semanticDescription' => 'Siroko M2 Riemst es un maillot de manga larga hombre para hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Vezzana', 'semanticDescription' => 'Siroko M2 Vezzana es un maillot de manga larga hombre para hombre. Disponible en Azul, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Triplet', 'semanticDescription' => 'Siroko M2 Triplet es un maillot de manga larga hombre para hombre. Disponible en Burdeos, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX Rainfall', 'semanticDescription' => 'Siroko SRX Rainfall es un perneras térmicas repelentes al agua para ciclistas. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Fassa', 'semanticDescription' => 'Siroko BX Fassa es un culote corto ciclismo hombre para hombre. Disponible en Gris, Blanco. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Umbrail', 'semanticDescription' => 'Siroko BX Umbrail es un culote corto ciclismo hombre para hombre. Disponible en Azul navy, Blanco. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Oberwald', 'semanticDescription' => 'Siroko BX Oberwald es un culote corto ciclismo hombre para hombre. Disponible en Verde militar, Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Bionaz', 'semanticDescription' => 'Siroko BX Bionaz es un culote corto ciclismo hombre para hombre. Disponible en Burdeos, Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Stage', 'semanticDescription' => 'Siroko SRX Stage es un maillot de manga corta hombre ultraligero para hombre. Disponible en Verde oliva. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Climb', 'semanticDescription' => 'Siroko SRX Climb es un maillot de manga corta hombre ultraligero para hombre. Disponible en Gris perla. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'S1 Cyan Trollstigen', 'semanticDescription' => 'Siroko S1 Cyan Trollstigen es un calcetines para ciclismo para ciclistas. Disponible en Cian. Confeccionado en Nailon y Elastano.'],
        ['name' => 'SRX M4 Volta', 'semanticDescription' => 'Siroko SRX M4 Volta es un maillot ciclismo térmico hombre para hombre. Disponible en Verde militar, Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Forecast', 'semanticDescription' => 'Siroko Forecast es un perneras térmicas ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX M4 Atlantis', 'semanticDescription' => 'Siroko SRX M4 Atlantis es un maillot ciclismo térmico hombre para hombre. Disponible en Amarillo neón, Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'Aero White', 'semanticDescription' => 'Siroko Aero White es un guantes ciclismo para ciclistas. Disponible en Blanco. Confeccionado en Nailon y Poliuretano y Poliéster y Elastano.'],
        ['name' => 'Aero Green', 'semanticDescription' => 'Siroko Aero Green es un guantes ciclismo para ciclistas. Disponible en Verde. Confeccionado en Nailon y Poliuretano y Poliéster y Elastano.'],
        ['name' => 'Aero Dark Blue', 'semanticDescription' => 'Siroko Aero Dark Blue es un guantes ciclismo para ciclistas. Disponible en Azul. Confeccionado en Nailon y Poliuretano y Poliéster y Elastano.'],
        ['name' => 'Aero Black', 'semanticDescription' => 'Siroko Aero Black es un guantes ciclismo para ciclistas. Disponible en Negro. Confeccionado en Nailon y Poliuretano y Poliéster y Elastano.'],
        ['name' => 'J2 Tourmalet', 'semanticDescription' => 'Siroko J2 Tourmalet es un chaquetas de lluvia ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliuretano.'],
        ['name' => 'SRX M4 Fleet Moss', 'semanticDescription' => 'Siroko SRX M4 Fleet Moss es un maillot ciclismo térmico hombre para hombre. Disponible en Negro, Gris. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX M4 Cubilla', 'semanticDescription' => 'Siroko SRX M4 Cubilla es un maillot ciclismo térmico hombre para hombre. Disponible en Azul navy, Azul eléctrico. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'BX Envalira', 'semanticDescription' => 'Siroko BX Envalira es un culote largo ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Bolzano', 'semanticDescription' => 'Siroko BX Bolzano es un culote largo ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Supreme', 'semanticDescription' => 'Siroko SRX Supreme es un culote largo ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Black Sea', 'semanticDescription' => 'Siroko Black Sea es un culote largo ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'S1 Pink Agnello', 'semanticDescription' => 'Siroko S1 Pink Agnello es un calcetines para ciclismo para ciclistas. Disponible en Rosa chicle. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Coral Mauna Kea', 'semanticDescription' => 'Siroko S1 Coral Mauna Kea es un calcetines para ciclismo para ciclistas. Disponible en Coral. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Olive Sa Calobra', 'semanticDescription' => 'Siroko S1 Olive Sa Calobra es un calcetines para ciclismo para ciclistas. Disponible en Verde oliva. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Fluor Montseny', 'semanticDescription' => 'Siroko S1 Fluor Montseny es un calcetines para ciclismo para ciclistas. Disponible en Amarillo neón. Confeccionado en Nailon y Elastano.'],
        ['name' => 'Flandrien', 'semanticDescription' => 'Siroko Flandrien es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'M3 Grand Master', 'semanticDescription' => 'Siroko M3 Grand Master es un maillot de manga corta hombre ultraligero para hombre. Disponible en Negro, Verde oliva. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Podium', 'semanticDescription' => 'Siroko M3 Podium es un maillot de manga corta hombre ultraligero para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M3 Peyresourde', 'semanticDescription' => 'Siroko M3 Peyresourde es un maillot de manga corta hombre ultraligero para hombre. Disponible en Violeta, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Essential Cap', 'semanticDescription' => 'Siroko Essential Cap es un gorro térmico para ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX Roselend', 'semanticDescription' => 'Siroko SRX Roselend es un maillot de manga larga hombre ultraligero para hombre. Disponible en Negro, Naranja intenso. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Manguitos Climatik', 'semanticDescription' => 'Siroko Manguitos Climatik es un manguitos ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'S1 Orange Flanders', 'semanticDescription' => 'Siroko S1 Orange Flanders es un calcetines para ciclismo para ciclistas. Disponible en Naranja intenso. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Red Flamme Rouge', 'semanticDescription' => 'Siroko S1 Red Flamme Rouge es un calcetines para ciclismo para ciclistas. Disponible en Rojo. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Maroon Volata', 'semanticDescription' => 'Siroko S1 Maroon Volata es un calcetines para ciclismo para ciclistas. Disponible en Burdeos. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Green Alpe d\'Huez', 'semanticDescription' => 'Siroko S1 Green Alpe d\'Huez es un calcetines para ciclismo para ciclistas. Disponible en Verde militar. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Blue Ancares', 'semanticDescription' => 'Siroko S1 Blue Ancares es un calcetines para ciclismo para ciclistas. Disponible en Azul navy. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 White Gavia', 'semanticDescription' => 'Siroko S1 White Gavia es un calcetines para ciclismo para ciclistas. Disponible en Blanco. Confeccionado en Nailon y Elastano.'],
        ['name' => 'S1 Black Kapelmuur', 'semanticDescription' => 'Siroko S1 Black Kapelmuur es un calcetines para ciclismo para ciclistas. Disponible en Negro. Confeccionado en Nailon y Elastano.'],
        ['name' => 'Braga cuello microfibra Climastar', 'semanticDescription' => 'Siroko Braga cuello microfibra Climastar es un braga coolmax ciclismo para ciclistas. Disponible en Gris. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Ultra Polar', 'semanticDescription' => 'Siroko Ultra Polar es un braga térmica ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Poliéster y Elastano.'],
        ['name' => 'M2 Westfalia', 'semanticDescription' => 'Siroko M2 Westfalia es un maillot de manga corta hombre para hombre. Disponible en Blanco, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Manguitos Térmicos ColdBlock', 'semanticDescription' => 'Siroko Manguitos Térmicos ColdBlock es un manguitos ciclismo para ciclistas. Disponible en Negro. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'SRX Ardiden', 'semanticDescription' => 'Siroko SRX Ardiden es un maillot de manga corta hombre ultraligero para hombre. Disponible en Blanco. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Altea', 'semanticDescription' => 'Siroko SRX Altea es un maillot de manga corta hombre ultraligero para hombre. Disponible en Naranja intenso. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'J1 Furkapass', 'semanticDescription' => 'Siroko J1 Furkapass es una chaqueta softshell ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'J1 Ordino', 'semanticDescription' => 'Siroko J1 Ordino es una chaqueta softshell ciclismo hombre para hombre. Disponible en Verde militar. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'J1 Soulor', 'semanticDescription' => 'Siroko J1 Soulor es una chaqueta softshell ciclismo hombre para hombre. Disponible en Burdeos. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'J1 Elba', 'semanticDescription' => 'Siroko J1 Elba es una chaqueta softshell ciclismo hombre para hombre. Disponible en Azul navy. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'SRX Typhoon', 'semanticDescription' => 'Siroko SRX Typhoon es una camiseta interior lana hombre para hombre. Disponible en Negro. Confeccionado en Lana Merino.'],
        ['name' => 'M2 Colorado', 'semanticDescription' => 'Siroko M2 Colorado es un maillot de manga corta hombre para hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Arizona', 'semanticDescription' => 'Siroko M2 Arizona es un maillot de manga larga hombre para hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX Dirty Kanza', 'semanticDescription' => 'Siroko SRX Dirty Kanza es un maillot de manga corta hombre ultraligero para hombre. Disponible en Burdeos. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Dauphiné', 'semanticDescription' => 'Siroko SRX Dauphiné es un maillot de manga corta hombre ultraligero para hombre. Disponible en Verde militar. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Tirreno', 'semanticDescription' => 'Siroko SRX Tirreno es un maillot de manga corta hombre ultraligero para hombre. Disponible en Azul navy. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'M2 Alpine', 'semanticDescription' => 'Siroko M2 Alpine es un maillot de manga larga hombre para hombre. Disponible en Azul navy, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX World Series', 'semanticDescription' => 'Siroko SRX World Series es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'SRX Elite', 'semanticDescription' => 'Siroko SRX Elite es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Resistance', 'semanticDescription' => 'Siroko BX Resistance es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'BX Squadra', 'semanticDescription' => 'Siroko BX Squadra es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Mortirolo', 'semanticDescription' => 'Siroko Mortirolo es un culote corto ciclismo hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'Aspen', 'semanticDescription' => 'Siroko Aspen es un culote corto ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'M2 Bavaria', 'semanticDescription' => 'Siroko M2 Bavaria es un maillot de manga larga hombre para hombre. Disponible en Azul navy, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX HighTech', 'semanticDescription' => 'Siroko SRX HighTech es un maillot de manga corta hombre ultraligero para hombre. Disponible en Negro. Confeccionado en Nailon y Poliéster y Elastano.'],
        ['name' => 'M2 Summit', 'semanticDescription' => 'Siroko M2 Summit es un maillot de manga larga hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Dirty Road', 'semanticDescription' => 'Siroko M2 Dirty Road es un maillot de manga corta hombre para hombre. Disponible en Verde militar. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Legend', 'semanticDescription' => 'Siroko M2 Legend es un maillot de manga larga hombre para hombre. Disponible en Negro, Azul eléctrico. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Leader', 'semanticDescription' => 'Siroko M2 Leader es un maillot de manga larga hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Gravel', 'semanticDescription' => 'Siroko M2 Gravel es un maillot de manga larga hombre para hombre. Disponible en Verde militar. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Road Trip', 'semanticDescription' => 'Siroko M2 Road Trip es un maillot de manga larga hombre para hombre. Disponible en Burdeos, Azul claro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Rider', 'semanticDescription' => 'Siroko M2 Rider es un maillot de manga larga hombre para hombre. Disponible en Negro, Rojo. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'V1 Blaast', 'semanticDescription' => 'Siroko V1 Blaast es un chaleco cortavientos ciclismo hombre para hombre. Disponible en Negro. Confeccionado en Poliéster.'],
        ['name' => 'M2 Mount Evans', 'semanticDescription' => 'Siroko M2 Mount Evans es un maillot de manga corta hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Hardknott Pass', 'semanticDescription' => 'Siroko M2 Hardknott Pass es un maillot de manga corta hombre para hombre. Disponible en Azul navy, Azul claro. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Finisher', 'semanticDescription' => 'Siroko M2 Finisher es un maillot de manga corta hombre para hombre. Disponible en Negro, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'M2 Riedberg', 'semanticDescription' => 'Siroko M2 Riedberg es un maillot de manga corta hombre para hombre. Disponible en Azul, Gris, Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'SRX SpeedMax', 'semanticDescription' => 'Siroko SRX SpeedMax es un maillot de manga larga hombre ultraligero para hombre. Disponible en Azul. Confeccionado en Poliéster y Poliamida y Elastano.'],
        ['name' => 'S1 Fucsia Barillete', 'semanticDescription' => 'Siroko S1 Fucsia Barillete es un calcetines para ciclismo para ciclistas. Disponible en Morado. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'S1 Ochre Major', 'semanticDescription' => 'Siroko S1 Ochre Major es un calcetines para ciclismo para ciclistas. Disponible en Marrón. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Albulapass Light Blue', 'semanticDescription' => 'Siroko Albulapass Light Blue es un calcetines retro para esquí para ciclistas. Disponible en Azul. Confeccionado en Algodón y Poliamida y Poliéster y Elastano.'],
        ['name' => 'Albulapass White', 'semanticDescription' => 'Siroko Albulapass White es un calcetines retro para esquí para ciclistas. Disponible en Blanco. Confeccionado en Algodón y Poliamida y Poliéster y Elastano.'],
        ['name' => 'Fuji Brown', 'semanticDescription' => 'Siroko Fuji Brown es un calcetines para snowboard para ciclistas. Disponible en Marrón. Confeccionado en Algodón y Poliéster y Poliamida y Elastano.'],
        ['name' => 'Fuji White', 'semanticDescription' => 'Siroko Fuji White es un calcetines para snowboard para ciclistas. Disponible en Blanco. Confeccionado en Algodón y Poliéster y Poliamida y Elastano.'],
        ['name' => 'Fuji Olive Green', 'semanticDescription' => 'Siroko Fuji Olive Green es un calcetines para snowboard para ciclistas. Disponible en Verde. Confeccionado en Algodón y Poliéster y Poliamida y Elastano.'],
        ['name' => 'Fuji Light Blue', 'semanticDescription' => 'Siroko Fuji Light Blue es un calcetines para snowboard para ciclistas. Disponible en Azul. Confeccionado en Algodón y Poliamida y Poliéster y Elastano.'],
        ['name' => 'Player-W Green', 'semanticDescription' => 'Siroko Player-W Green es un polo técnico media cremallera tenis mujer para mujer. Disponible en Verde. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Player White', 'semanticDescription' => 'Siroko Player White es un polo técnico media cremallera tenis hombre para hombre. Disponible en Blanco. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Player Navy', 'semanticDescription' => 'Siroko Player Navy es un polo técnico media cremallera tenis hombre para hombre. Disponible en Azul. Confeccionado en Poliamida y Elastano.'],
        ['name' => 'Volley-W White', 'semanticDescription' => 'Siroko Volley-W White es un pantalones acampanados tenis mujer para mujer. Disponible en Blanco. Confeccionado en Poliéster y Elastano.'],
        ['name' => 'Volley-W Navy', 'semanticDescription' => 'Siroko Volley-W Navy es un pantalones acampanados tenis mujer para mujer. Disponible en Azul. Confeccionado en Poliéster y Elastano.'],
    ];

    public function __construct(private readonly MessageBusInterface $commandBus)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $io->title('Seeding Siroko products');

        $created = 0;
        $indexed = 0;
        $errors  = 0;

        foreach (self::PRODUCTS as $data) {
            try {
                $command = new CreateProductCommand($data['name'], $data['semanticDescription']);
                $this->commandBus->dispatch($command);
                ++$created;

                $this->commandBus->dispatch(new IndexProductCommand($command->id));
                ++$indexed;
            } catch (\Throwable $e) {
                ++$errors;
                $io->error(sprintf('[%s] %s', $data['name'], $e->getMessage()));
            }
        }

        $io->success(sprintf('Creados: %d | Indexados: %d | Errores: %d', $created, $indexed, $errors));

        return Command::SUCCESS;
    }
}
