framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

        pools:
            cache.embeddings:
                adapter: cache.adapter.redis
                default_lifetime: 300

