services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/*/Domain/'

    App\Product\Domain\Repository\ProductRepository:
        alias: App\Product\Infrastructure\Persistence\Doctrine\DoctrineProductRepository
